class OutputGuard:
    """
    Validates the final response generated by the LLM.

    The receptionist should not provide medical diagnosis,
    prescriptions, or treatment advice.
    """

    BLOCKED_PATTERNS = {
        "you have",
        "you likely have",
        "you probably have",
        "diagnosis is",
        "i diagnose",
        "take this medicine",
        "you should take",
        "prescription for",
        "recommended dosage",
        "your dosage should be",
    }

    SAFE_FALLBACK = (
        "I can help with clinic information, doctors, "
        "services, availability, and contact details. "
        "For medical diagnosis or treatment advice, "
        "please consult a qualified healthcare professional."
    )

    def check(self, response: str) -> tuple[bool, str]:
        """
        Validate an LLM-generated response.

        Returns:
            (allowed, final_response)
        """

        if not isinstance(response, str):
            return False, self.SAFE_FALLBACK

        response = response.strip()

        if not response:
            return False, self.SAFE_FALLBACK

        normalized_response = response.lower()

        for pattern in self.BLOCKED_PATTERNS:
            if pattern in normalized_response:
                return False, self.SAFE_FALLBACK

        return True, response